### ISSUE TITLE
BattleWordle: nothing happens when an invalid word is entered by user

### ISSUE THREAD

**Issue by limagisele** [team-alembic/playdate#117]

**Comment by mbuhot** [comment]
I think we can set an assign here: https://github.com/team-alembic/playdate/blob/266b67c716b56484bef3f41db0fab0163f6c8392/lib/playdate/games/battle_wordle/ui/game_live.ex#L112-L113

after an invalid guess, and render an error indicator when the guess in not valid.

**Comment by limagisele** [comment]
fixed in #118
