### ISSUE TITLE
Header: Weird animation when loading - only sometimes.

### ISSUE THREAD

**Issue by jimsynz** [team-alembic/playdate#123]
This is likely to be a heisenbug, but here's a video of it happening.

![navbar-slide-in](https://user-images.githubusercontent.com/59449/191354746-900912c2-0f47-4344-b996-6bd553bd1714.gif)

**Comment by thmsmtylr** [comment]
Fixed with: https://github.com/team-alembic/playdate/commit/27c04e33a3e07a6778fb690d3fbc57c872435e6f
