### ISSUE TITLE
Header: inconsistent login button.

### ISSUE THREAD

**Issue by jimsynz** [team-alembic/playdate#124]
On small displays, the hamburger menu shows the login option as a "secondary" button:

<img width="612" alt="Screen Shot 2022-09-21 at 8 10 08 AM" src="https://user-images.githubusercontent.com/59449/191355212-bad7b00d-a910-4b3a-bd36-a2c888e2f9bd.png">

On medium and up, the navbar shows the login option as just red text which quite low contrast against the black background:

<img width="788" alt="Screen Shot 2022-09-21 at 8 10 20 AM" src="https://user-images.githubusercontent.com/59449/191355339-2f5c4e4b-fbd4-4c08-999f-4f9cf6cdc142.png">

**Comment by thmsmtylr** [comment]
@jimsynz You're right the log in is a little bit `squinty` so I've used the secondary button.
<img width="1260" alt="Screen Shot 2022-09-21 at 11 23 43 am" src="https://user-images.githubusercontent.com/5527769/191393440-bd1ef420-c93d-47f7-a3bb-1eb5756da1b4.png">

This should be resolved in: https://github.com/team-alembic/playdate/pull/126

**Comment by jimsynz** [comment]
Nice. If you comment with `Closes #124` in your PR then it will automatically close this issue when the PR is merged.

**Comment by thmsmtylr** [comment]
Dang missed this will close manually.
